queue_rules:
  - name: dep-updates
    batch_size: 10
    batch_max_wait_time: 30 min
    queue_conditions:
      - base=main
      - author=dependabot[bot]
      - label=dependencies
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    merge_conditions:
      - status-success=Semantic Pull Request
      - status-success=Check Python library
      - status-success=Check Typescript library
      - status-success=Check Python-based Time Server
      - status-success=Check Typescript-based Weather Alerts Server
      - status-success=Check Typescript chatbot
    merge_method: squash

pull_request_rules:
  - name: Automatically merge Dependabot PRs
    conditions:
      - base=main
      - author=dependabot[bot]
      - label=dependencies
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      queue:
