import { resolve } from "path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    setupFiles: ["./test/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      exclude: [
        "node_modules/",
        "dist/",
        "build/",
        "coverage/",
        "**/*.d.ts",
        "**/*.config.*",
        "**/test/**",
        "**/tests/**",
        "**/__tests__/**",
        "**/*.test.*",
        "**/*.spec.*",
        "**/mocks/**",
        "**/fixtures/**",
        "**/stories/**",
        "**/.storybook/**",
        "**/cypress/**",
        "**/playwright/**",
        "**/e2e/**",
        "**/integration/**",
        "**/examples/**",
        "**/docs/**",
        "**/scripts/**",
        "**/tools/**",
        "**/bin/**",
        "**/cli/**",
        "**/config/**",
        "**/types/**",
        "**/interfaces/**",
        "**/schemas/**",
        "**/migrations/**",
        "**/seeds/**",
        "**/factories/**",
        "**/helpers/**",
        "**/utils/**",
        "**/constants/**",
        "**/enums/**",
        "**/middleware/**",
        "**/validators/**",
        "**/transformers/**",
        "**/adapters/**",
        "**/ports/**",
        "**/infrastructure/**",
        "**/presentation/**",
        "**/application/**",
        "**/domain/**",
        "**/shared/**",
        "**/common/**",
        "**/core/**",
        "**/base/**",
        "**/abstract/**",
        "**/interfaces/**",
        "**/types/**",
        "**/schemas/**",
        "**/migrations/**",
        "**/seeds/**",
        "**/factories/**",
        "**/helpers/**",
        "**/utils/**",
        "**/constants/**",
        "**/enums/**",
        "**/middleware/**",
        "**/validators/**",
        "**/transformers/**",
        "**/adapters/**",
        "**/ports/**",
        "**/infrastructure/**",
        "**/presentation/**",
        "**/application/**",
        "**/domain/**",
        "**/shared/**",
        "**/common/**",
        "**/core/**",
        "**/base/**",
        "**/abstract/**",
      ],
      thresholds: {
        global: {
          branches: 70,
          functions: 70,
          lines: 70,
          statements: 70,
        },
        "./src/domain/": {
          branches: 80,
          functions: 80,
          lines: 80,
          statements: 80,
        },
        "./src/application/": {
          branches: 75,
          functions: 75,
          lines: 75,
          statements: 75,
        },
        "./src/infrastructure/": {
          branches: 65,
          functions: 65,
          lines: 65,
          statements: 65,
        },
      },
      all: true,
      include: [
        "src/**/*.{ts,tsx}",
        "packages/**/src/**/*.{ts,tsx}",
        "applications/**/src/**/*.{ts,tsx}",
      ],
    },
    reporters: ["verbose", "html"],
    outputFile: {
      html: "./coverage/index.html",
    },
  },
  resolve: {
    alias: {
      "@demo/shared": resolve(__dirname, "./packages/shared/src"),
      "@demo/types": resolve(__dirname, "./packages/types/src"),
      "@demo/infrastructure": resolve(__dirname, "./infrastructure/aws/src"),
    },
  },
});
